from pathlib import Path

OUT = Path(__file__).parent

STYLE = r'''#set page(paper: "a4", margin: (top: 22mm, bottom: 20mm, left: 22mm, right: 22mm), numbering: "1")
#set text(font: "Noto Sans", size: 10.2pt, fill: rgb("173247"))
#set par(justify: true, leading: 0.85em, spacing: 0.65em)
#set heading(numbering: none)
#show heading.where(level: 1): it => block(above: 0pt, below: 10pt)[#text(size: 19pt, weight: "bold", fill: rgb("0a6f72"))[#it.body]]
#show heading.where(level: 2): it => it.body
#let accent = rgb("0fa987")
#let navy = rgb("173247")
#let muted = rgb("66808e")
#let callout(title, body) = block(fill: rgb("eaf6f3"), stroke: (left: 3pt + accent), radius: 5pt, inset: 10pt, width: 100%)[*#title*\\ #body]
#let table-row(a,b) = table.cell(fill: rgb("f2f7f8"))[#a] + table.cell(fill: rgb("f2f7f8"))[#b]
#align(right)[#text(size: 8pt, fill: muted)[BLOCKCHAIN TRUST ENTERPRISE · LEARNING DESK]]
'''

GUIDES = [
("copy-trading-guide", "Copy Trading: A Practical Risk-First Guide", "How to evaluate strategies, set guardrails, and learn without surrendering control", [
("How to use this guide", "Copy trading lets an account mirror another trader or strategy. It can simplify execution, but it does not transfer responsibility, remove market risk, or guarantee the copied result. Treat this guide as education, not a recommendation to copy any person or strategy.", "Start with a written objective: what you are trying to learn, the maximum loss you can tolerate, and the conditions under which you will stop."),
("1 · What copy trading is", "A copy-trading arrangement links a follower account to a source account or model. The platform may mirror entries, exits, position sizes, or allocations according to rules. Timing, liquidity, fees, slippage, leverage, and account differences can make results diverge.", "Key distinction: copying an action is not the same as understanding the thesis behind that action."),
("2 · How the mechanism works", "Before enabling a strategy, map the data path: source signal, platform interpretation, order creation, exchange or broker execution, and portfolio reporting. Identify whether the platform has custody, trading authority, or only read access.", "Ask what happens when the source trades an asset unavailable in your account, when an order partially fills, or when the connection is interrupted."),
("3 · Evaluating a strategy", "A short winning period is weak evidence. Review the full available history, maximum drawdown, volatility, losing streaks, turnover, leverage, concentration, fees, and whether the record is live or simulated. Prefer transparent methodology over impressive marketing.", "Never judge a strategy by return alone. Pair return with drawdown, downside exposure, and the conditions that produced the result."),
("4 · Provider and platform due diligence", "Confirm identity, operating history, fee schedule, conflicts, withdrawal rules, permissions, security controls, complaint channels, and the legal entity behind the service. Be cautious when a provider pressures you to act immediately or promises consistent returns.", "A professional-looking dashboard is not proof of solvency, competence, or legitimacy."),
("5 · Risk controls before activation", "Set a small initial allocation, a maximum position size, a portfolio-level loss limit, a leverage ceiling of zero unless you fully understand it, and a stop-copy rule. Use separate credentials or API keys with trading-only permissions where available; never allow withdrawals through an API key.", "Write the controls down before the first trade. Controls chosen after a loss are usually too late."),
("6 · Monitoring and intervention", "Review copied positions, realized and unrealized P/L, fees, exposure by asset, and deviations from the source. Establish a review cadence. Pause when the source changes style, the platform changes terms, execution quality degrades, or you can no longer explain the exposure.", "Automation should make monitoring easier, not make monitoring optional."),
("7 · Common failure modes", "Common problems include stale signals, slippage, latency, overconcentration, hidden leverage, liquidation cascades, fee drag, strategy drift, and false performance reporting. Operational failures—lost access, outages, or weak account security—can be as damaging as market losses.", "Maintain a manual exit plan and know how to revoke permissions quickly."),
("8 · A measured learning workflow", "Use a staged process: observe, paper-test, allocate a limited amount, review results, and only then decide whether the strategy remains suitable. Keep an evidence log with dates, assumptions, decisions, and outcomes. Separate educational curiosity from money you need for living expenses.", "The goal is not to find a perfect trader; it is to build a process that remains survivable when the trader is wrong."),
("9 · Checklist and closing notes", "Before copying, confirm: objective, source history, fees, permissions, custody, liquidity, drawdown, concentration, leverage, loss limit, stop-copy process, tax records, and support contacts. Copy trading can be useful as a learning tool, but every account owner remains responsible for their own risk decisions.", "Disclosure: Digital assets and trading can lose some or all of their value. Seek independent professional advice for your circumstances."),
]),
("crypto-digital-assets-guide", "Crypto & Digital Assets: A Foundation Guide", "Networks, wallets, custody, transactions, and practical security habits", [
("How to use this guide", "Digital assets are issued, transferred, or recorded using distributed-ledger or blockchain technology. This guide explains foundational concepts and safety practices. It is educational and does not endorse any asset, platform, or investment strategy.", "Assume that every transaction is irreversible until you have independently verified the destination, network, and amount."),
("1 · The digital-asset landscape", "Digital assets can include native network assets, tokens, stablecoins, governance tokens, collectibles, and tokenized claims. Their technical design, legal treatment, liquidity, and risks can differ materially. Labels are not substitutes for due diligence.", "Ask what the asset does, who controls upgrades, how supply changes, and where liquidity comes from."),
("2 · Blockchains and consensus", "A blockchain is a shared record maintained by a network under rules for validating transactions. Consensus mechanisms determine how updates are accepted. Finality, confirmation time, fees, and reorganization risk vary across networks.", "A transaction can be visible on-chain before it is economically or operationally final for your use case."),
("3 · Wallets and keys", "A wallet manages keys that authorize transactions; it does not store coins in the same way a physical wallet stores cash. A seed phrase or private key is effectively control of the associated assets. Anyone who obtains it may be able to move funds.", "Never share a seed phrase, private key, or signing approval. No legitimate support agent needs it."),
("4 · Custody choices", "Self-custody provides direct control but places backup, device, and transaction responsibility on the user. Third-party custody may offer recovery and operational controls but introduces counterparty, insolvency, access, and policy risk.", "Choose custody based on capability, amount, access needs, and recovery planning—not brand familiarity alone."),
("5 · Sending and receiving safely", "Verify the asset, network, address, memo or tag, and amount. Use a small test transaction when appropriate. Compare the address on the signing device, not only the screen that requested the transfer. Be aware of address poisoning and clipboard malware.", "A correct-looking address can still belong to the wrong network or recipient."),
("6 · Smart contracts and approvals", "Interacting with a smart contract can authorize transfers or other actions. Read the requested allowance and scope. Revoke unnecessary approvals using a reputable tool, and separate experimental activity from long-term holdings.", "A signature request is not automatically safe because it appears in a familiar wallet."),
("7 · Stablecoins, bridges, and platforms", "Stablecoins depend on reserve, redemption, governance, and market mechanisms. Bridges add technical and operational dependencies. Exchanges and platforms add counterparty and withdrawal risk. Diversification of custodians can reduce single-point exposure but adds complexity.", "Understand the failure mode of every intermediary in your transaction path."),
("8 · Fraud and account security", "Impersonation, fake support, phishing, malicious browser extensions, giveaway scams, and fabricated investment dashboards are common attack patterns. Use unique passwords, hardware-based multi-factor authentication where possible, device updates, transaction alerts, and bookmarks for important services.", "Urgency, secrecy, guaranteed returns, and requests for remote access are strong warning signs."),
("9 · Personal operating checklist", "Keep an inventory of wallets and custodians, recovery instructions, trusted contacts, transaction records, tax documents, and emergency procedures. Start with small amounts while learning. Never risk rent, emergency savings, or borrowed money.", "Disclosure: Digital assets are volatile and may become illiquid or permanently inaccessible. Regulations and tax treatment vary by jurisdiction; consult qualified professionals."),
]),
("memecoin-safety-guide", "Memecoins & Rug-Pull Safety", "A practical framework for recognizing hype, testing claims, and limiting irreversible loss", [
("How to use this guide", "Memecoins are highly speculative tokens often driven by culture, attention, and community narratives rather than established cash flows. Some are legitimate experiments; others are designed to extract funds. No checklist can guarantee safety, so the strongest protection is limiting exposure.", "Treat every new memecoin as capable of going to zero, becoming unsellable, or being associated with fraud."),
("1 · What makes memecoins different", "Memecoin prices can move rapidly on thin liquidity and social momentum. Ownership concentration, automated trading, token mechanics, and influencer attention can dominate price discovery. A large community or viral post is not proof of quality.", "Separate popularity from verifiable information about contract control, liquidity, and distribution."),
("2 · Rug pulls and exit scams", "A rug pull generally involves insiders or developers removing value, abusing privileged controls, or abandoning a project after attracting buyers. Related scams include honeypots that block selling, fake presales, impersonated launches, and pump-and-dump coordination.", "The user’s loss can occur even when the token’s website and social channels look polished."),
("3 · Contract and control checks", "Check whether ownership is renounced or governed, whether minting, pausing, blacklisting, fee, and upgrade functions exist, and who can call them. Use multiple independent block explorers and reputable security tools; automated scores are signals, not guarantees.", "A renounced contract can still have economic risks such as concentrated holders or weak liquidity."),
("4 · Liquidity and sellability", "Review liquidity size, lock or custody claims, unlock dates, pool concentration, trading volume quality, and whether sell transactions succeed for ordinary wallets. A high price with shallow liquidity may be impossible to exit without severe slippage.", "Buy-side activity alone does not demonstrate that the market is safely sellable."),
("5 · Holder concentration and insider risk", "Inspect top-holder balances, deployer-linked wallets, coordinated transfers, vesting claims, and wallet clusters. Concentration increases the chance that a few sales can overwhelm liquidity. Beware of wallets that appear separate but fund one another.", "Do not confuse a high holder count with distributed ownership."),
("6 · Marketing red flags", "Warning signs include guaranteed returns, countdown pressure, secret allocations, celebrity endorsements without verification, anonymous teams claiming institutional backing, paid reviews presented as independent research, and requests to disable critical comments.", "If the pitch depends on urgency, assume the opportunity cost of waiting is smaller than the cost of rushing."),
("7 · Wallet and transaction safety", "Use a separate wallet for experimentation. Never connect a primary wallet to an unknown site. Verify the domain, chain, contract address, approvals, and transaction simulation. Keep funds for fees separate, and revoke approvals after use.", "A token airdrop or unsolicited NFT can be a lure to a malicious contract."),
("8 · A risk-limited decision process", "Define a maximum amount before researching, use no leverage, avoid borrowed funds, stage any purchase rather than rushing, and set an exit or stop condition. Record the thesis and invalidate it when facts change. If you cannot explain the token’s sell path, do not proceed.", "The safest position in a memecoin is often no position; education does not create an obligation to buy."),
("9 · Final safety checklist", "Before interacting, verify the official contract through multiple channels, contract permissions, liquidity and unlocks, holder concentration, sellability, team disclosures, audit limitations, wallet hygiene, and your maximum loss. Report suspected fraud to the relevant platform and authorities, preserve transaction hashes, and do not send more money to recover a loss.", "Disclosure: This is educational content, not investment advice. Memecoins can lose all value, and on-chain transactions may be irreversible."),
]),
]


def esc(s: str) -> str:
    return s.replace("&", "\\&").replace("#", "\\#")

for slug, title, subtitle, pages in GUIDES:
    lines = [STYLE]
    lines += [f"#align(center)[#v(28mm) #text(size: 30pt, weight: \"bold\", fill: navy)[{esc(title)}] #v(8mm) #text(size: 13pt, fill: accent)[{esc(subtitle)}] #v(25mm) #line(length: 65%, stroke: 2pt + accent) #v(10mm) #text(size: 10pt, fill: muted)[Blockchain Trust Enterprise · Learning Desk] #v(8mm) #text(size: 9pt, fill: muted)[Educational resource · Version 1.0 · September 2026]]"]
    for i, (head, body, box) in enumerate(pages):
        lines += ["#pagebreak()", f"= {esc(head)}", f"{esc(body)}", f"#v(8mm)", f"#callout(\"Practical note\", [{esc(box)}])"]
        if i == len(pages)-1:
            lines += ["#v(12mm)", "#text(size: 8pt, fill: muted)[Sources and further reading: Investor.gov copy trading glossary; FINRA Crypto Assets; SEC Investor Alert on crypto-asset scams; IOSCO investor-education publications. These resources provide general education and do not validate any particular service or token.]", "#v(4mm)", "#text(size: 8pt, fill: muted)[For the latest links, visit investor.gov, finra.org, sec.gov, and iosco.org.]"]
    (OUT / f"{slug}.typ").write_text("\n".join(lines) + "\n", encoding="utf-8")
