'use client';

import { FormEvent, useState } from 'react';
import { ArrowRight, CheckCircle2, ShieldCheck } from 'lucide-react';

export default function AccountPage() {
  const [mode, setMode] = useState<'register' | 'login'>('register');
  const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(''); setMessage(''); try { const response = await fetch('/api/operations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(mode === 'register' ? { action: 'register', fullName, email, password } : { action: 'login', email, password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); localStorage.setItem('bte-user-token', data.token); localStorage.setItem('bte-user', JSON.stringify(data.user)); setMessage(mode === 'register' ? 'Demo account created. Your BTE workspace is ready.' : 'Signed in successfully. Your BTE workspace is ready.'); } catch (err) { setError(err instanceof Error ? err.message : 'Request failed.'); } finally { setLoading(false); } }
  return <main className="account-page"><section className="account-hero"><a className="account-brand" href="/">BTE <span>Blockchain Trust Enterprises</span></a><div className="account-copy"><div className="eyebrow"><span className="eyebrow-line" />BTE client access</div><h1>Build conviction with more control.</h1><p>Create a paper account to explore copy trading, strategy research, guardrails, and explainable execution before any production integration is enabled.</p><div className="account-proof"><span><CheckCircle2 size={16} />Paper workspace included</span><span><ShieldCheck size={16} />Risk controls first</span></div></div></section><section className="account-card"><div className="account-tabs"><button className={mode === 'register' ? 'active' : ''} onClick={() => setMode('register')}>Create account</button><button className={mode === 'login' ? 'active' : ''} onClick={() => setMode('login')}>Sign in</button></div><h2>{mode === 'register' ? 'Create your BTE workspace' : 'Welcome back to BTE'}</h2><p className="account-muted">{mode === 'register' ? 'Use an email you control. This preview creates a demo account only.' : 'Sign in to continue to your demo workspace.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Full name<input value={fullName} onChange={(e) => setFullName(e.target.value)} required placeholder="Jordan Morgan" /></label>}<label>Email address<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required placeholder="you@example.com" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={8} placeholder="At least 8 characters" /></label>{error && <div className="account-error">{error}</div>}{message && <div className="account-success">{message} <a href="/account/dashboard">Open dashboard <ArrowRight size={14} /></a></div>}<button className="primary-button account-submit" disabled={loading}>{loading ? 'Securing workspace…' : mode === 'register' ? 'Create demo account' : 'Sign in'} <ArrowRight size={16} /></button></form><p className="account-disclaimer">Demo mode only. No funds are accepted and no live orders are routed.</p></section></main>;
}
